### ISSUE TITLE
unable to create alidns-secret

### ISSUE THREAD

**Issue by hillbun** [pragkent/alidns-webhook#11]
```
apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
data:
  access-key: LTAI4G6adCiyQacpG1******
  secret-key: 6nK5bwzcuYzEzRb279ibmCyI******
```

error：

`Error from server (BadRequest): error when creating "alidns-secret.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 28, error found in #10 byte of ...|CyI1D6WPn"},"kind":"|..., bigger context ...|Vtt","secret-key":"6nK5bwzcuYzEzRb279ibmCyI******"},"kind":"Secret","metadata":{"annotations":{"kube|...`
