### ISSUE TITLE
It appears that only single domain cert are supported

### ISSUE THREAD

**Issue by Iceber** [pragkent/alidns-webhook#17]
cert:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: icebergu-tls
spec:
  secretName: icebergu-com-tls
  commonName: icebergu.com
  dnsNames:
  - icebergu.com
  uris:
  - "www.icebergu.com"
  - "blog.icebergu.com"
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-staging
    kind: ClusterIssuer
```
csr:
```
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:icebergu.com, URI:www.icebergu.com, URI:blog.icebergu.com
```
cert:
```
            X509v3 Subject Alternative Name: 
                DNS:icebergu.com
```
