### ISSUE TITLE
The third-level domain name wildcard certificate does not work

### ISSUE THREAD

**Issue by qingfengfenga** [pragkent/alidns-webhook#18]
The third-level wildcard domain name does not work, what should I do? Is it because Let's Encrypt does not support it?

![image](https://user-images.githubusercontent.com/41416092/134868523-89654a2d-27c8-4742-b6ec-86f7bc87f63c.png)

Example：

*.xxx.xxx.com

**Comment by mayocream** [comment]
Let's Encrypt **does** support it, we have third-level wildcard domain certificates signed by Let's Encrypt.

**Comment by basilhe** [comment]
@qingfengfenga 
add more dnsNames in the cluster issuer
<pre>
dnsNames:
  - xxx.com
  - xxx.xxx.com
  - '*.xxx.com'
  - '*.xxx.xxx.com'
 </pre>

and create certificate for the third-level wildcard domain with commonName and dnsNames as follows, it works
<pre>
  commonName: 'xxx.xxx.com'
  dnsNames:
  - xxx.xxx.com
  - '*.xxx.xxx.com'
</pre>

**Comment by Learntotolearn** [comment]
I also encountered this problem. Here are some of my configurations:
```
spec:
  dnsNames:
  - xx.vip
  - '*.xx.vip'
  - '*.ws.xx.vip'
  issuerRef:
    kind: ClusterIssuer
    name: aliyun
  secretName: https-certificates

```

**Comment by qingfengfenga** [comment]
From @basilhe 
This is my configuration format, which can be used normally in my environment. I hope it can help you 

```
spec:
  secretName: tls
  commonName: x.x.com
  dnsNames:
  - x.x.com
  - "*.x.x.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
```
